"use client";

import React, { useState, useEffect } from "react";
import {
  getNotebooks,
  deleteNotebook,
  createNotebook,
  renameNotebookName,
} from "@/Server/notebook";
import { insertNotebook, Notes } from "@/db/schema";
import { Card, CardHeader, CardTitle, CardDescription } from "./ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "./ui/dropdown-menu";
import { Button } from "./ui/button";
import {
  Edit2Icon,
  EllipsisVertical,
  Eye,
  Loader2,
  Plus,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "./ui/alert-dialog";
import { Input } from "./ui/input";
import { authClient } from "@/lib/auth-client";
import { Skeleton } from "./ui/skeleton";
import { convertDate } from "@/lib/date-converter";

interface Notebook extends insertNotebook {
  id: string;
  name: string;
  notes: Notes[];
}

function NoteBooks() {
  const [notebooks, setNotebooks] = useState<Notebook[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedNotebook, setSelectedNotebook] = useState<Notebook | null>(
    null
  );
  const [notebookCreateLoading, setNotebookCreateLoading] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isRenameDialogOpen, setIsRenameDialogOpen] = useState(false);
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false);
  const [notebookName, setNotebookName] = useState("");
  const [newNotebookName, setNewNotebookName] = useState("");
  const router = useRouter();

  useEffect(() => {
    fetchNotebooks();
  }, []);

  const fetchNotebooks = async () => {
    try {
      setLoading(true);
      const { notebooks } = await getNotebooks();
      if (!notebooks) {
        toast.error("Failed to load notebooks");
        return;
      }
      setNotebooks(notebooks);
      setLoading(false);
    } catch (error) {
      console.error("Error fetching notebooks:", error);
      toast.error("Failed to load notebooks");
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteClick = (notebook: Notebook) => {
    setSelectedNotebook(notebook);
    setIsDeleteDialogOpen(true);
  };

  const handleRenameClick = async (id: string) => {
    const notebook = notebooks.find((notebook) => notebook.id === id) || null;
    setSelectedNotebook(notebook);
    if (!notebook) return;
    setNewNotebookName(notebook.name);
    setIsRenameDialogOpen(true);
  };
  const handleCreateNotebookClick = () => {
    setIsCreateDialogOpen(true);
  };
  const confirmDelete = async () => {
    if (!selectedNotebook) return;

    try {
      await deleteNotebook(selectedNotebook.id);
      toast.success("Notebook deleted successfully");
      fetchNotebooks();
    } catch (error) {
      console.error("Error deleting notebook:", error);
      toast.error("Failed to delete notebook");
    } finally {
      setIsDeleteDialogOpen(false);
      setSelectedNotebook(null);
    }
  };

  const handleRename = async () => {
    if (!newNotebookName?.trim() || !selectedNotebook?.id) return;
    try {
      const result = await renameNotebookName({
        id: selectedNotebook?.id,
        name: newNotebookName,
      });
      if (!result.success) {
        toast.error(result.message);
        return;
      }
      toast.success(result.message);
      fetchNotebooks();
    } catch (error) {
      console.error("Error renaming notebook:", error);
      toast.error("Failed to rename notebook");
      // reload for the Changes
      router.refresh();
    } finally {
      setIsRenameDialogOpen(false);
      setSelectedNotebook(null);
    }
  };
  // accept only notebook name and user id to create other properties are generated by the database (by default) so there is no need to pass them and get error about them

  const handleCreateNotebook = async (notebookName: string) => {
    // Navigate to create notebook page or open a modal
    // get userId from sessionstorage
    // loading state with specific className
    setNotebookCreateLoading(true);
    const session = await authClient.getSession();
    const userId = session?.data?.user?.id;
    if (!userId) {
      toast.error("User not authenticated" + userId);
      return;
    }
    try {
      toast.success("Notebook created successfully");
      await createNotebook({ name: notebookName, userId });
      setNotebookCreateLoading(false);
      // refresh to show the new notebook
      fetchNotebooks();
    } catch (error) {
      console.error("Error creating notebook:", error);
      toast.error("Failed to create notebook");
      setNotebookCreateLoading(false);
    }
  };
  const handleNotebookClick = async (notebook: Notebook) => {
    // add url to the existing url with out removing
    router.push(`dashboard/notebooks/${notebook.id}`);
  };

  if (loading) {
    // skeleton on loading
    return (
      <div className="w-[95%] mx-auto grid grid-cols-3 mt-12 gap-4">
        {Array.from({ length: 12 }).map((_, i) => (
          <Skeleton key={i} className="h-28 w-full mr-2 rounded-lg" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-4 mx-4 mt-4 ">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold">My Notebooks</h2>
        <Button onClick={handleCreateNotebookClick} className="w-40">
          {notebookCreateLoading ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            <div className="flex items-center">
              <Plus className="mr-2 h-4 w-4" />
              New Notebook
            </div>
          )}
        </Button>
      </div>
      {/** when the user only  click notebook card  it should navigatet to the details page otherwise it should open the ellipsis menu */}
      {notebooks.length === 0 ? (
        <div className="text-center py-12 border-2 border-dashed rounded-lg">
          <p className="text-muted-foreground">No notebooks found</p>
          {/* <Button
            variant="outline"
            className="mt-4"
            onClick={handleCreateNotebook}
          >
            Create your first notebook
          </Button> */}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {notebooks.map((notebook) => (
            <Card
              key={notebook.id}
              className="hover:shadow-md transition-shadow hover:border-b-accent-foreground hover:transition-all hover:scale-[1.005] hover:duration-200 hover:ease-in-out hover:cursor-pointer"
            >
              <CardHeader className="flex flex-row justify-between items-start space-y-0">
                <div
                  className="space-y-1 "
                  onClick={() => handleNotebookClick(notebook)}
                >
                  <CardTitle className="text-lg flex flex-row justify-between items-center max-w-32">
                    <h2 className="line-clamp-1">{notebook.name}</h2>
                    <span className="text-xs text-muted-foreground bg-accent rounded-full px-2 py-1 relative -top-2   ">
                      {notebook?.notes?.length || 0}
                    </span>
                  </CardTitle>
                  {/*date and time */}
                  <CardDescription className="text-xs text-muted-foreground">
                    {notebook.updatedAt
                      ? `Updated: ${convertDate(notebook.updatedAt)}`
                      : notebook.createdAt
                      ? `Created at: ${convertDate(notebook.createdAt)}`
                      : "N/A"}
                  </CardDescription>
                </div>
                <DropdownMenu>
                  <DropdownMenuTrigger
                    asChild
                    className="cursor-pointer hover:border hover:border-accent-foreground hover:transition-all hover:scale-[1.005] hover:duration-200 hover:ease-in-out"
                  >
                    <Button variant="ghost" size="icon" className="h-8 w-8 ">
                      <EllipsisVertical className="h-4 w-4" />
                      <span className="sr-only hover:cursor-pointer">
                        More actions
                      </span>
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem
                      onClick={() => handleRenameClick(notebook.id)}
                    >
                      <Edit2Icon className="mr-2 h-4 w-4" />
                      <span>Rename</span>
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      className="text-destructive focus:text-destructive"
                      onClick={() => handleDeleteClick(notebook)}
                    >
                      <Trash2 className="mr-2 h-4 w-4" />
                      <span>Delete</span>
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </CardHeader>
              {/** button to view details */}
              <Button
                variant="secondary"
                size="icon"
                className="ml-2 hover:bg-accent-foreground hover:text-accent  hover:ease-in-out hover:duration-500"
                onClick={() => handleNotebookClick(notebook)}
              >
                <Eye className="h-4 w-4 " />
                <span className="sr-only hover:cursor-pointer">
                  View details
                </span>
              </Button>
            </Card>
          ))}
        </div>
      )}

      {/* Delete Confirmation Dialog */}
      <AlertDialog
        open={isDeleteDialogOpen}
        onOpenChange={setIsDeleteDialogOpen}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete the notebook "
              {selectedNotebook?.name}" and all its contents. This action cannot
              be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={confirmDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Rename Dialog */}
      <AlertDialog
        open={isRenameDialogOpen}
        onOpenChange={setIsRenameDialogOpen}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Rename Notebook</AlertDialogTitle>
            <AlertDialogDescription>
              Enter a new name for the notebook.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="py-4">
            <Input
              value={newNotebookName}
              onChange={(e) => setNewNotebookName(e.target.value)}
              placeholder="Notebook name"
              autoFocus
            />
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleRename}
              disabled={!newNotebookName?.trim()}
            >
              Save Changes
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
      {/** Create Notebook dialog box */}
      <AlertDialog
        open={isCreateDialogOpen}
        onOpenChange={setIsCreateDialogOpen}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Create Notebook</AlertDialogTitle>
            <AlertDialogDescription>
              Enter a name for the notebook.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="py-4">
            <Input
              value={notebookName}
              onChange={(e) => setNotebookName(e.target.value)}
              placeholder="Notebook name"
              autoFocus
            />
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => handleCreateNotebook(notebookName)}
              disabled={!notebookName.trim()}
            >
              Create Notebook
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

export default NoteBooks;
