import { insertNotebook, notebook } from "@/db/schema";
import { db } from "@/db/drizzle";
import { eq } from "drizzle-orm";
interface renameNotebookProps {
  id: string;
  name: string;
}
export const getNotebooks = async () => {
  try {
    const notebooks = await db.select().from(notebook);
    return { success: true, data: JSON.stringify(notebooks) };
  } catch (error) {
    const e = error as Error;
    return { success: false, message: e.message || "Failed to get notebooks" };
  }
};
//only name and userId are expected from the client the rest are generated by the database by default
export const createNotebook = async ({ name, userId }: insertNotebook) => {
  try {
    await db.insert(notebook).values({ name, userId });
    return { success: true, message: "Notebook created successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to create notebook",
    };
  }
};
export const renameNotebook = async ({ id, name }: renameNotebookProps) => {
  try {
    await db.update(notebook).set({ name }).where(eq(notebook.id, id));
    return { success: true, message: "Notebook renamed successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to rename notebook",
    };
  }
};
export const deleteNotebook = async (id: string) => {
  try {
    await db.delete(notebook).where(eq(notebook.id, id));
    return { success: true, message: "Notebook deleted successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to delete notebook",
    };
  }
};
