"use server";
import { insertNotebook, notebooks, typeNotebook } from "@/db/schema";
import { db } from "@/db/drizzle";
import { and, eq } from "drizzle-orm";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
interface renameNotebookProps {
  id: string;
  name: string;
}
const getUserId = async (): Promise<string | undefined> => {
  const session = await auth.api.getSession({ headers: await headers() });
  const userId = session?.user.id;
  if (!userId) {
    return undefined;
  }
  return userId;
};
export const getNotebooks = async () => {
  try {
    const userId = await getUserId();
    if (!userId) {
      return { success: false, notebooks: [] };
    }
    // return notebooks with notes under them
    const result = await db.query.notebooks.findMany({
      where: eq(notebooks.userId, userId),
      with: {
        notes: true,
      },
    });
    return { success: true, notebooks: result };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      notebooks: [],
      message: e.message || "Failed to get notebooks",
    };
  }
};
// get notebook by id
export const getNotebookById = async ({ id }: typeNotebook) => {
  try {
    const userId = await getUserId();
    if (!userId) {
      return { success: false, message: "Unauthorized" };
    }
    const result = await db.query.notebooks.findFirst({
      where: and(eq(notebooks.id, id), eq(notebooks.userId, userId)),
    });
    return { success: true, notebook: result };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to get notebook by id",
    };
  }
};
//only name and userId are expected from the client the rest are generated by the database by default
export const createNotebook = async ({ name }: insertNotebook) => {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    const userId = session?.user.id;
    if (!userId) {
      return { success: false, message: "User is not found" };
    }
    await db.insert(notebooks).values({ name, userId });
    return { success: true, message: "Notebook created successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to create notebook",
    };
  }
};
export const renameNotebook = async ({ id, name }: renameNotebookProps) => {
  try {
    await db.update(notebooks).set({ name }).where(eq(notebooks.id, id));
    return { success: true, message: "Notebook renamed successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to rename notebook",
    };
  }
};
export const deleteNotebook = async (id: string) => {
  try {
    await db.delete(notebooks).where(eq(notebooks.id, id));
    return { success: true, message: "Notebook deleted successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to delete notebook",
    };
  }
};
