import { insertNotebook, notebook, typeNotebook } from "@/db/schema";
import { db } from "@/db/drizzle";
import { eq } from "drizzle-orm";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { success } from "zod";
interface renameNotebookProps {
  id: string;
  name: string;
}
const getUserId = async (): Promise<string | undefined> => {
  const session = await auth.api.getSession({ headers: await headers() });
  const userId = session?.user.id;
  if (!userId) {
    return undefined;
  }
  return userId;
};
export const getNotebooks = async () => {
  try {
    const userId = await getUserId();
    if (!userId) {
      return { success: false, message: "User is not found" };
    }
    const notebooks = await db
      .select()
      .from(notebook)
      .where(eq(notebook.userId, userId));
    return { success: true, data: notebooks };
  } catch (error) {
    const e = error as Error;
    return { success: false, message: e.message || "Failed to get notebooks" };
  }
};
// get notebook by id
export const getNotebookById = async ({ id }: typeNotebook) => {
  try {
    const data = db.select().from(notebook).where(eq(notebook.id, id));
    return { success: true, data: data };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to get notebook by id",
    };
  }
};
//only name and userId are expected from the client the rest are generated by the database by default
export const createNotebook = async ({ name }: insertNotebook) => {
  try {
    const session = await auth.api.getSession({ headers: await headers() });
    const userId = session?.user.id;
    if (!userId) {
      return { success: false, message: "User is not found" };
    }
    await db.insert(notebook).values({ name, userId });
    return { success: true, message: "Notebook created successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to create notebook",
    };
  }
};
export const renameNotebook = async ({ id, name }: renameNotebookProps) => {
  try {
    await db.update(notebook).set({ name }).where(eq(notebook.id, id));
    return { success: true, message: "Notebook renamed successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to rename notebook",
    };
  }
};
export const deleteNotebook = async (id: string) => {
  try {
    await db.delete(notebook).where(eq(notebook.id, id));
    return { success: true, message: "Notebook deleted successfully" };
  } catch (error) {
    const e = error as Error;
    return {
      success: false,
      message: e.message || "Failed to delete notebook",
    };
  }
};
